- name: Create directory
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory

- name: Import PostgreSQL key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

- name: Allow PostgreSQL in the firewall
  community.general.ufw:
    rule: allow
    port: "5432"
    proto: tcp

- name: Add PostgreSQL debian repo
  deb822_repository:
    name: pgdg
    types:
      - deb
      - deb-src
    uris: https://apt.postgresql.org/pub/repos/apt
    suites: trixie-pgdg
    architectures: amd64
    components:
      - main
    signed_by: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL 16 & required dependencies
  ansible.builtin.apt:
    pkg:
      - postgresql-16
      - python3-psycopg2 # Required to create the database
    state: present

- name: Copy configuration file
  register: postgresql_conf
  ansible.builtin.copy:
    src: files/postgresql.conf
    dest: /etc/postgresql/16/main/postgresql.conf

- name: Copy pg_hba.conf file
  register: pg_hba
  ansible.builtin.copy:
    src: files/pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf

- name: Restart PostgreSQL DB
  when: pg_hba.changed or postgresql_conf.changed
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Create paul user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgresql_username }}"
    password: "{{ postgresql_password }}"

- name: Create the database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"

- name: Grant all privilieges to the database for user
  community.postgresql.postgresql_privs:
    login_db: "{{ postgresql_db }}"
    privs: ALL
    type: database
    objs: "{{ postgresql_db }}"
    role: "{{ postgresql_username }}"

- name: Create directory
  ansible.builtin.file:
    path: /var/lib/pgsql
    state: directory

- name: Copy application
  register: schema
  ansible.builtin.copy:
    src: files/schema.sql
    dest: /var/lib/pgsql/schema.sql

- name: Run query from SQL schema
  when: schema.changed
  become: true
  become_user: postgres
  community.postgresql.postgresql_script:
    login_db: "{{ postgresql_db }}"
    path: /var/lib/pgsql/schema.sql

- name: Grant all privilieges to the votes table for user
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    login_db: "{{ postgresql_db }}"
    privs: ALL
    type: table
    objs: votes
    role: "{{ postgresql_username }}"
