- name: Create directory
  become: true
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: "0755"

- name: Import PostgreSQL key
  become: true
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: "0644"

- name: Allow PostgreSQL in the firewall
  become: true
  community.general.ufw:
    rule: allow
    port: "5432"
    proto: tcp
    src: "{{ item }}"
  loop:
    - "{{ hostvars['result-1']['ansible_host'] }}"
    - "{{ hostvars['poll-1']['ansible_host'] }}"
    - "{{ hostvars['worker-1']['ansible_host'] }}"

- name: Add PostgreSQL debian repo
  become: true
  ansible.builtin.deb822_repository:
    name: pgdg
    types:
      - deb
      - deb-src
    uris: https://apt.postgresql.org/pub/repos/apt
    suites: trixie-pgdg
    architectures: amd64
    components:
      - main
    signed_by: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install PostgreSQL 16 & required dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - postgresql-16
      - python3-psycopg2 # Required to create the database
    state: present

- name: Copy configuration file
  become: true
  register: postgresql_conf
  ansible.builtin.copy:
    src: files/postgresql.conf
    dest: /etc/postgresql/16/main/postgresql.conf
    mode: "0644"

- name: Copy pg_hba.conf file
  become: true
  register: postgresql_hba
  ansible.builtin.copy:
    src: files/pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf
    mode: "0644"

- name: Restart PostgreSQL DB
  become: true
  when: postgresql_hba.changed or postgresql_conf.changed
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Create paul user
  become: true
  community.postgresql.postgresql_user:
    name: "{{ postgresql_username }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: LOGIN,NOSUPERUSER,NOCREATEDB,NOCREATEROLE,NOINHERIT

- name: Create the database
  become: true
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"

- name: Create directory
  become: true
  ansible.builtin.file:
    path: /var/lib/pgsql
    state: directory
    mode: "0755"

- name: Copy application
  become: true
  register: postgresql_schema
  ansible.builtin.copy:
    src: files/schema.sql
    dest: /var/lib/pgsql/schema.sql
    mode: "0644"

- name: Run query from SQL schema
  when: postgresql_schema.changed
  become: true
  community.postgresql.postgresql_script:
    login_db: "{{ postgresql_db }}"
    path: /var/lib/pgsql/schema.sql

- name: Grant some privilieges to the votes table for user
  become: true
  community.postgresql.postgresql_privs:
    login_db: "{{ postgresql_db }}"
    privs: SELECT,INSERT,UPDATE
    type: table
    objs: votes
    role: "{{ postgresql_username }}"
