- name: Install Redis
  become: true
  ansible.builtin.apt:
    pkg:
      - redis
    state: present

- name: Copy configuration
  become: true
  ansible.builtin.copy:
    src: files/redis.conf
    dest: /etc/redis/redis.conf
    mode: "0644"
  notify:
    - Restart redis

- name: Allow Redis in the firewall
  become: true
  community.general.ufw:
    rule: allow
    port: "6379"
    proto: tcp
    src: "{{ item }}"
  loop:
    - "{{ hostvars['result-1']['ansible_host'] }}"
    - "{{ hostvars['poll-1']['ansible_host'] }}"
    - "{{ hostvars['worker-1']['ansible_host'] }}"

- name: Enable redis
  become: true
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
