- name: Install Redis
  ansible.builtin.apt:
    pkg:
      - redis
    state: present

- name: Copy configuration
  ansible.builtin.copy:
    src: files/redis.conf
    dest: /etc/redis/redis.conf

- name: Allow Redis in the firewall
  community.general.ufw:
    rule: allow
    port: "6379"
    proto: tcp

- name: Enable redis
  service:
    name: redis-server
    state: started
    enabled: true
