---
- name: Base role
  hosts: all
  roles:
    - role: "base"

- name: Redis database
  hosts: redis
  roles:
    - role: "redis"

- name: PostgreSQL database
  hosts: postgresql
  roles:
    - role: "postgresql"

- name: Poll application
  hosts: poll
  roles:
    - role: "poll"

- name: Result application
  hosts: result
  roles:
    - role: "result"

- name: Worker application
  hosts: worker
  roles:
    - role: "worker"
