---
- name: Base role
  hosts: all
  roles:
    - role: "roles/base"

- name: Redis database
  hosts: redis
  roles:
    - role: "roles/redis"

- name: PostgreSQL database
  hosts: postgresql
  roles:
    - role: "roles/postgresql"

- name: Poll application
  hosts: poll
  roles:
    - role: "roles/poll"

- name: Result application
  hosts: result
  roles:
    - role: "roles/result"

- name: Worker application
  hosts: worker
  roles:
    - role: "roles/worker"
