- name: Install maven & OpenJDK 21
  ansible.builtin.apt:
    pkg:
      - maven
      - openjdk-21-jdk
    state: present

- name: Create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Copy application
  ansible.builtin.copy:
    src: ../../../worker.tar
    dest: /app/worker.tar

- name: Unarchive the application
  register: unarchiving
  ansible.builtin.unarchive:
    src: /app/worker.tar
    dest: /app
    remote_src: true

- name: Install dependencies
  when: unarchiving.changed
  command: mvn dependency:resolve
  args:
    chdir: /app/worker

- name: Package jar file
  command: mvn package
  args:
    chdir: /app/worker
    creates: /app/worker/target/worker-jar-with-dependencies.jar

- name: Copy systemd service
  register: systemd_service
  ansible.builtin.template:
    src: files/worker.service
    dest: /etc/systemd/system/worker.service

- name: Enable application service
  when: systemd_service.changed
  ansible.builtin.service:
    name: worker
    state: restarted
    enabled: true
