- name: Install essential packages
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
      - ca-certificates
      - tar
      - ufw
    state: present

- name: Set timezone to Europe/Paris
  become: true
  community.general.timezone:
    name: Europe/Paris

- name: Set a hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Enable firewall
  become: true
  community.general.ufw:
    state: enabled

- name: Allow OpenSSH in the firewall
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH
